### ISSUE TITLE
notifyItemChanged an GridSLM

### ISSUE THREAD

**Issue by jermeyyy** [TonicArtos/SuperSLiM#119]
Sending notifyItemChanged casues other items (usually 2 other items on in grid) to flicker when using GridSLM, problem is not present when using LinearSLM. Any other specific info available on request.

**Comment by TonicArtos** [comment]
This is a known problem. I am working on it.

**Comment by jermeyyy** [comment]
Do you have any clue what is causing that? Do you need any help with that? Any ETA on fix?

**Comment by TonicArtos** [comment]
I never got to fully supporting data changes because it turns out just using views to track state was complicated and bug prone. I've started on a rewrite to fix these problems and make the library much more simple to use and to maintain. I've been [blogging](http://tonicartos.com) about my thoughts on the library design and what I've managed to do with the time I have.

As for the ETA, I hope to have a very stripped down alpha available in the next week. I am hoping people will use the alpha to give me feedback on what it is like to use. If that goes well, I'll move onto adding the grid layout and other features back into the library.
