### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#16]

**Comment by mabdurrahman** [comment]
Hi @TonicArtos 

This fix is now partially broken, i've an issue on Grid Layout in RTL where the first view in a row starts to the Left instead of Right, and i found that replacing the next code:
```
// File: GridSLM.java, Method: fillRow(int markerLine, int anchorPosition, LayoutManager.Direction direction, boolean measureRowItems, SectionData sd, LayoutState state);
layoutChild(views[col], markerLine, col, rowHeight, sd, state);
```
with the code that was previously introduced by this commit, it works fine:
```
// File: GridSLM.java, Method: fillRow(int markerLine, int anchorPosition, LayoutManager.Direction direction, boolean measureRowItems, SectionData sd, LayoutState state);
layoutChild(views[col], markerLine, state.isLTR ? col : mNumColumns - 1 - col, rowHeight, sd, state);
```
And I found that you've removed this fix in this commit: https://github.com/TonicArtos/SuperSLiM/commit/fbad7b65cecec8864eb8e8391bc8485b8c54a80a

**Comment by TonicArtos** [comment]
Thanks, I was surprised to learn I had missed picking this up.

**Comment by TonicArtos** [comment]
@mabdurrahman Thank you for your feedback on this issue. Please let me know if there are any other issues with RTL support.
