### ISSUE TITLE
Initialization thoughts.

### ISSUE THREAD

**Issue by PatrickDattilio** [TonicArtos/SuperSLiM#41]
I'd like to discuss the initialization process. Right now, the initialization code for SuperSLiM is a bit verbose:

```java
layoutManager = new LayoutManager();
headerManager = new LinearSectionLayoutManager(layoutManager);
layoutManager.registerSectionLayoutManager(0, headerManager);
gridManager = new GridSectionLayoutManager(layoutManager, getActivity());
gridManager.setNumColumns(3);
layoutManager.registerSectionLayoutManager(1, gridManager);
recyclerView.setLayoutManager(layoutManager);
```
We currently have to initialize the all SLM's (including the default SLM's) ourselves, keep track of the index and correctly match these in our view binding/xml.

I would love to be able to do something like:
```java
layoutManager = LayoutManager.enableLinearSLM().enableGridSLM(context, 3).addCustomSLM(new MySLM()).build()
recyclerView.setLayoutManager(layoutManager);
```
We could then use some sort of tag so then
```java
final LayoutManager.LayoutParams lp = (LayoutManager.LayoutParams) holder.itemView.getLayoutParams();
lp.sectionManager = 0
```
would become something like
```java
lp.setSLM(LinearSLM.tag)
```

I'm not sure how this would work via XML, but this shows exactly what SLM is being used without having to switch from your adapter to recyclerview implementation to match up ids.

**Comment by TonicArtos** [comment]
So I have some of my own ideas on this too, I've added them below, but first I'd like to ask for a clarification.

How should your proposal handle multiple configurations of the same SLM?

Okay, on to my thoughts.

I have actually been thinking about this lots. First, this was because I wanted to move SLM referencing and configuration to only the first item in the section. I remember there was some technical reason why I couldn't, but I can't remember it right now and I forgot to write it down, so I guess it warrants another look.

I completely agree with the issue of verbosity and boilerplate in initialisation. My thoughts actually turned to an idea of adding enum options to the sectionManager attr. This has also included adding pass through attrs for SLM configuration through attrs too.

For example, configuration for using grid layout on content items:
```xml
<!-- TextView as a section header. -->
<TextView
    app:slm_sectionManager="grid"
    app:slm_grid_numColumns="4"
    app:slm_grid_minimumColumnWidth="96dp"
    />
```
This would also mean configuration through layout params:
```java
GridSectionLayoutManager.LayoutParams params = 
    new GridSectionLayoutManager.LayoutParams(viewHolder.getLayoutParams());
params.setSectionManager(LayoutManager.GRID_LAYOUT);
params.setMinimumColumnWidth(R.dimen.minumum_column_width);
// or
params.setNumColumns(4);
```
For custom SLMs there still needs to be a key to identify them. Perhaps an SLM could be registered against a String value to make identification easy, or the documentation can encourage people to use R.integer.my_slm_id, or perhaps R.id.my_slm.

**Comment by TonicArtos** [comment]
Ah yes, I just looked through the code and I've rediscovered why the section manager needs to be referenced, and configured, in every item. The entry points for calculating the scroll indicator values don't provide the recycler so I can't get the first item of a section if it isn't current displayed.

However, I guess I can get around it by caching section data. Now that I think about it, it seems feasible.

**Comment by PatrickDattilio** [comment]
I like the enum, very straightforward. Perhaps add an abstract enum to SectionLayoutManager, forcing all SLM's to implement/extend the enum themselves. I haven't written much in terms of custom xml tags, but would this allow us to do the following?
```xml
<TextView
    app:slm_sectionManager="myEnum"
    />
```

**Comment by TonicArtos** [comment]
That would be nice, unfortunately the enums are defined here https://github.com/TonicArtos/SuperSLiM/blob/master/library/src/main/res/values/attrs.xml

**Comment by TonicArtos** [comment]
I can do something like

```xml
<attr name="slm_sectionManager" format="enum|string|reference" />
```

but I think enum|reference is good. I'll experiment when I look at it.

**Comment by PatrickDattilio** [comment]
Ah I see. I like your idea of registering a String, a set id reminds me of the unintuitive @id/android:list for ListFragments.

**Comment by TonicArtos** [comment]
Well, enum|string will make the interface look the same for custom layouts as for the internal ones, but you need to `addSLM("myslm", new MySLM())`.

**Comment by PatrickDattilio** [comment]
Oh nice! That looks perfect to me.

**Comment by TonicArtos** [comment]
It does look pretty good.

**Comment by PatrickDattilio** [comment]
This might be a good candidate for 3.0, as the layoutId->sectionManager is an API breaking change.

**Comment by TonicArtos** [comment]
I am going straight to 0.4.
