### ISSUE TITLE
Documentation improvements.

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#79]
When the next major version is released there will be a lot of changes, and is a big reason why I haven't work on improving the current documentation further. However, if you can suggest the kinds the of things you found difficult about the documentation in this version, I can use that knowledge to improve it for the next.

**Comment by ThanosFisherman** [comment]
Just a few suggestions. It took me a while to figure out how things work because the code quotes in Getting Started guide didn't match the code in sample app. For example it would be nice to refer in the docs how and why you came up with codes such as  `holder.setLayoutParams(params);` and `holder.getLayoutParams();` Also it'd be nice to explain a few things about the `holder.bindItem(item);`

Now about the sample app I felt like the code is kind of rough. You can implement the Holder polymorphism pattern like we did on my issue #75 and maybe make the code cleaner generally.

That's all for now I may come back later with more suggestions

**Comment by AAverin** [comment]
Would be good to have things like headerDisplay and other parameters documented.
And yes, sample code and example app do not match, so it's completely unclear how to use the library at the moment.
