### ISSUE TITLE
Data change animations

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#8]

**Comment by TonicArtos** [comment]
Will require support from SLMs.

**Comment by kingargyle** [comment]
So I take it right now the Layout Managers for 0.4.x do not support animations?

**Comment by TonicArtos** [comment]
Some things work from notify data set changed with one of the recent recycler view updates. I am working on this for 0.5, right now in fact.

**Comment by RJFares** [comment]
I added an ItemAnimator for my recyclerview.
It seems that animations don't work as intended if used with SLM since each row needs to be recalculated, am I correct? The only one that made sense was notifyDataSetChanged(). Not as smooth smooth as one wants but waiting for a better solution.

**Comment by DennyWeinberg** [comment]
Currently I am trying to get smooth UI updates done using Androids DiffUtil: https://android.jlelse.eu/smart-way-to-update-recyclerview-using-diffutil-345941a160e0

It works not so bad, but when I try to remove items with the header at the same time, it crashes.

I have to try a bit more, maybe I can get it working.
As you said, we need to recalculate the sectionFirstPosition of all items. In general this is no problem because we can use onBindViewHolder payloads in order to refresh only a part.

**Comment by TonicArtos** [comment]
I am surprised you got it working as well as that.

**Comment by DennyWeinberg** [comment]
I didn't worked 100%. Maybe 70% or something. But it should be possible for most of the cases with some more time. But I would say that it's the work of the library and not of the user, so I stopped my Tests after many crashes... :)

**Comment by TonicArtos** [comment]
I completely understand. I have had to hack around things for a long time too. I am partially using the new version now, and I don't have any problems with animations there. I just have to finish implementing the grid layout.
